### ISSUE TITLE
Add arg parsing, remove input()

### ISSUE THREAD

**Issue by Blank1611** [Blank1611/jsonmergeutils#1]
Currently, the utility uses input() funtions for fetching inputs/data from user. The script needs to be modified so that it accepts arguments from commandline
e.g
`jsonmerge_utils.py -ip test -op result -maxFileSize 600 -filepath /var/tmp/SampleJsonfiles`

-ip  Input prefix
-op Output prefix
-maxFileSize The maximum file size (in bytes) that each merged file should have
 -filepath path to dir where all json files are stored
-log_level [INFO, DEBUG, ERROR] Defaults to INFO

**Comment by MLJBrackett** [comment]
Hi @Blank1611 I'd like to help out, could I be assigned this issue?

**Comment by Blank1611** [comment]
Sure, done
